# Generated by Django 3.1 on 2020-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='descripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('permisos', models.CharField(blank=True, choices=[('crearproyecto', 'crearproyecto'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='crearproyecto', help_text='acciones que se le permitiran', max_length=50)),
                ('Lista_permisos', models.ManyToManyField(to='permiso.descripcion')),
            ],
        ),
    ]
