# Generated by Django 3.1 on 2020-09-01 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pro', models.CharField(max_length=50)),
                ('descripcion_pro', models.CharField(max_length=50)),
                ('tareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea.tarea')),
            ],
        ),
    ]
