# Generated by Django 3.0.3 on 2020-03-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permiso', models.CharField(max_length=50)),
                ('descripcion', models.CharField(help_text='Ingrese descripcion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(help_text='Ingrese el nombre del proyecto', max_length=50)),
                ('descripcion', models.CharField(help_text='Descripción del proyecto', max_length=200)),
                ('estado', models.CharField(blank=True, choices=[('a', 'Activo'), ('i', 'Inactivo'), ('f', 'Finalizado')], default='a', help_text='Estados del proyecto', max_length=1)),
            ],
            options={
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=50)),
                ('id_tarea_padre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del usuario', max_length=50)),
                ('apellido', models.CharField(help_text='Ingrese el apellido del usuario', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(help_text='Ingrese el nombre del rol', max_length=30)),
                ('descripcion', models.CharField(help_text='Ingrese descripcion', max_length=200)),
                ('permiso', models.ManyToManyField(help_text='Seleccione uno o más permisos', to='users.Permiso')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
    ]
