# Generated by Django 3.0.3 on 2020-03-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lb', models.CharField(help_text='Ingrese el nombre de la Linea Base', max_length=30)),
                ('descripcion', models.CharField(help_text='Ingrese descripcion', max_length=200)),
                ('tarea', models.ManyToManyField(help_text='Seleccione uno o más tareas', to='users.Tarea')),
            ],
        ),
    ]
